package io.github.kardeiro.gallery.ui.theme

import androidx.compose.ui.graphics.Color

// Fallback colors when dynamic color is unavailable
val FallbackPrimary = Color(0xFF006D40)
val FallbackOnPrimary = Color(0xFFFFFFFF)
val FallbackPrimaryContainer = Color(0xFF95F7B5)
val FallbackOnPrimaryContainer = Color(0xFF002111)
val FallbackSecondary = Color(0xFF4E6352)
val FallbackOnSecondary = Color(0xFFFFFFFF)
val FallbackSecondaryContainer = Color(0xFFD1E8D3)
val FallbackOnSecondaryContainer = Color(0xFF0C1F13)
val FallbackTertiary = Color(0xFF3D6473)
val FallbackOnTertiary = Color(0xFFFFFFFF)
val FallbackTertiaryContainer = Color(0xFFC0E9FB)
val FallbackOnTertiaryContainer = Color(0xFF001F29)
val FallbackBackground = Color(0xFFFBFDF8)
val FallbackOnBackground = Color(0xFF191C1A)
val FallbackSurface = Color(0xFFFBFDF8)
val FallbackOnSurface = Color(0xFF191C1A)
val FallbackSurfaceVariant = Color(0xFFDDE5DA)
val FallbackOnSurfaceVariant = Color(0xFF414941)
val FallbackSurfaceContainerLowest = Color(0xFFFFFFFF)
val FallbackSurfaceContainerLow = Color(0xFFF5F8F2)
val FallbackSurfaceContainer = Color(0xFFEFF2EC)
val FallbackSurfaceContainerHigh = Color(0xFFE9EDE7)
val FallbackSurfaceContainerHighest = Color(0xFFE3E7E1)
val FallbackOutline = Color(0xFF717970)
val FallbackOutlineVariant = Color(0xFFC1C9BE)
val FallbackScrim = Color(0xFF000000)
val FallbackError = Color(0xFFBA1A1A)
val FallbackOnError = Color(0xFFFFFFFF)
val FallbackErrorContainer = Color(0xFFFFDAD6)
val FallbackOnErrorContainer = Color(0xFF410002)

val DarkFallbackPrimary = Color(0xFF79DA9A)
val DarkFallbackOnPrimary = Color(0xFF00391F)
val DarkFallbackPrimaryContainer = Color(0xFF00522F)
val DarkFallbackOnPrimaryContainer = Color(0xFF95F7B5)
val DarkFallbackSecondary = Color(0xFFB5CCB8)
val DarkFallbackOnSecondary = Color(0xFF213527)
val DarkFallbackSecondaryContainer = Color(0xFF374B3C)
val DarkFallbackOnSecondaryContainer = Color(0xFFD1E8D3)
val DarkFallbackTertiary = Color(0xFFA4CDDE)
val DarkFallbackOnTertiary = Color(0xFF083542)
val DarkFallbackTertiaryContainer = Color(0xFF254C5A)
val DarkFallbackOnTertiaryContainer = Color(0xFFC0E9FB)
val DarkFallbackBackground = Color(0xFF111411)
val DarkFallbackOnBackground = Color(0xFFE1E4DE)
val DarkFallbackSurface = Color(0xFF111411)
val DarkFallbackOnSurface = Color(0xFFE1E4DE)
val DarkFallbackSurfaceVariant = Color(0xFF414941)
val DarkFallbackOnSurfaceVariant = Color(0xFFC1C9BE)
val DarkFallbackSurfaceContainerLowest = Color(0xFF0C0F0C)
val DarkFallbackSurfaceContainerLow = Color(0xFF191C1A)
val DarkFallbackSurfaceContainer = Color(0xFF1D211E)
val DarkFallbackSurfaceContainerHigh = Color(0xFF282B28)
val DarkFallbackSurfaceContainerHighest = Color(0xFF333633)
val DarkFallbackOutline = Color(0xFF8B9389)
val DarkFallbackOutlineVariant = Color(0xFF414941)
val DarkFallbackScrim = Color(0xFF000000)
val DarkFallbackError = Color(0xFFFFB4AB)
val DarkFallbackOnError = Color(0xFF690005)
val DarkFallbackErrorContainer = Color(0xFF93000A)
val DarkFallbackOnErrorContainer = Color(0xFFFFDAD6)
